### ISSUE TITLE
onEnd function called twice

### ISSUE THREAD

**Issue by FerLuisxd** [fastify/fastify-multipart#137]
## 🐛 Bug Report

Hello,  this is my first issue here, 
So basically the problem is that the response is sent twice

## To Reproduce

Below is a function that I export to the array of routes I use on another file, the route and implementation is fine, I've tested with other routes (that don't require this module). So it must be something about the onEnd being called twice? Am I doing something wrong? I think I've followed the readme example.

```js
exports.addNewStory =  (req, reply) => {
    try {
        if (!req.isMultipart()) {
            reply.code(400).send(new Error('Request is not multipart'))
          }
          const mp = req.multipart(handler, onEnd)
          mp.on('field', function (key, value) {
            console.log('form-data', key, value)
          })
          function onEnd(err) {
            console.log('upload completed',err)
            reply.code(200).send({message:'nice!'})
          }
          function handler (field, file, filename, encoding, mimetype) {
            let newPath = __dirname.substr(0, __dirname.length - 14) + '/temp/' + crypto.randomBytes(8).toString('hex') + filename.substr(filename.length-4,filename.length);
            pump(file, fs.createWriteStream(newPath),function(e){
                if(e) console.log(e)
            })
          }
    } catch (err) {
        return err
    }
}
```
```log
{"level":30,"time":1596088641495,"pid":65172,"hostname":"DESKTOP-T8DT8T8","reqId":3,"req":{"method":"POST","url":"/api/story","hostname":"localhost:3000","remoteAddress":"127.0.0.1","remotePort":62949},"msg":"incoming request"}
upload completed undefined
{"level":30,"time":1596088641508,"pid":65172,"hostname":"DESKTOP-T8DT8T8","reqId":3,"res":{"statusCode":212},"responseTime":12.456399023532867,"msg":"request completed"}
upload completed undefined
{"level":40,"time":1596088641510,"pid":65172,"hostname":"DESKTOP-T8DT8T8","reqId":3,"err":{"type":"FastifyError","message":"Reply was already sent.","stack":"FastifyError: Reply was already sent.\n    at _Reply.Reply.send (C:\\Users\\FerLuis\\Documents\\fbstoriesscheduler\\node_modules\\fastify\\lib\\reply.js:110:26)\n    at Immediate.onEnd [as _onImmediate] (C:\\Users\\FerLuis\\Documents\\fbstoriesscheduler\\src\\controller\\stories.js:44:29)\n    at processImmediate (internal/timers.js:456:21)","name":"FastifyError","code":"FST_ERR_REP_ALREADY_SENT","statusCode":500},"msg":"Reply already sent"}
```
## Expected behavior

```log
{"level":30,"time":1596088641495,"pid":65172,"hostname":"DESKTOP-T8DT8T8","reqId":3,"req":{"method":"POST","url":"/api/story","hostname":"localhost:3000","remoteAddress":"127.0.0.1","remotePort":62949},"msg":"incoming request"}
upload completed undefined
{"level":30,"time":1596088641508,"pid":65172,"hostname":"DESKTOP-T8DT8T8","reqId":3,"res":{"statusCode":212},"responseTime":12.456399023532867,"msg":"request completed"}
```

## Your Environment

- *node version*: 13.12
- *fastify version*: 3.1.1
- *fastify-multipart*: 2.0.3
- *os*: Windows

**Comment by mcollina** [comment]
Would you mind adding a self-contained example that reproduce the problem? We need to know what http body can cause this.

**Comment by mcollina** [comment]
Can you also check with Node v12 or v14, v13 is _unsupported_.

**Comment by FerLuisxd** [comment]
Thanks for the fast response! Will do tomorrow

**Comment by FerLuisxd** [comment]
You should be able to download this clone/ download this example
https://codesandbox.io/s/amazing-driscoll-s7wlg?file=/src/start.js

**Comment by mcollina** [comment]
```
/sandbox/node_modules/fastify/lib/route.js:136
      throw new Error(`Missing handler function for ${opts.method}:${opts.url} route.`)
      ^

Error: Missing handler function for POST:/api/story route.
    at Object.route (/sandbox/node_modules/fastify/lib/route.js:136:13)
    at Object._route [as route] (/sandbox/node_modules/fastify/fastify.js:200:27)
    at routesStories.forEach (/sandbox/src/start.js:9:7)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/sandbox/src/start.js:8:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

That's the error it has.

**Comment by Eomm** [comment]
I think you are missing a `return` statement here

```
if (!req.isMultipart()) {
            reply.code(400).send(new Error('Request is not multipart'))
          }
```

**Comment by FerLuisxd** [comment]
On me, I was using an async function when it was really not needed! My apologies! Will close this now
