### ISSUE TITLE
Cannot read properties of undefined (reading 'Symbol(multipartHandler)')

### ISSUE THREAD

**Issue by kolserdav** [fastify/fastify-multipart#416]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.13.0

### Plugin version

7.4.1

### Node.js version

v18.13.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Linux arch 6.0.11-arch1-1 

### Description

When sending files via multipart-/form-date, the request crashes with an error before reaching the request handler:
```sh
":{"method":"OPTIONS","url":"/v1/file-upload","hostname":"192.168.0.3:3001","remoteAddress":"192.168.0.3","remotePort":37262},"msg":"incoming request"}
[0] [1] [0] {"level":30,"time":1676620072948,"pid":85757,"hostname":"arch","reqId":"req-8","res":{"statusCode":204},"responseTime":0.5045800004154444,"msg":"request completed"}
[0] [1] [0] {"level":30,"time":1676620072955,"pid":85757,"hostname":"arch","reqId":"req-9","req":{"method":"POST","url":"/v1/file-upload","hostname":"192.168.0.3:3001","remoteAddress":"192.168.0.3","remotePort":37262},"msg":"incoming request"}
[0] [1] [0] {"level":50,"time":1676620072962,"pid":85757,"hostname":"arch","reqId":"req-9","req":{"method":"POST","url":"/v1/file-upload","hostname":"192.168.0.3:3001","remoteAddress":"192.168.0.3","remotePort":37262},"res":{"statusCode":500},"err":{"type":"TypeError","message":"Cannot read properties of undefined (reading 'Symbol(multipartHandler)')","stack":"TypeError: Cannot read properties of undefined (reading 'Symbol(multipartHandler)')\n    at getMultipartFile (/home/kol/Projects/safe/packages/server/node_modules/@fastify/multipart/index.js:588:23)\n    at Object.fileUpload (/home/kol/Projects/safe/packages/server/dist/api/v1/file/file-upload.js:9:21)\n    at preHandlerCallback (/home/kol/Projects/safe/packages/server/node_modules/fastify/lib/handleRequest.js:128:37)\n    at preValidationCallback (/home/kol/Projects/safe/packages/server/node_modules/fastify/lib/handleRequest.js:112:5)\n    at handler (/home/kol/Projects/safe/packages/server/node_modules/fastify/lib/handleRequest.js:76:7)\n    at /home/kol/Projects/safe/packages/server/node_modules/fastify/lib/contentTypeParser.js:192:9\n    at AsyncResource.runInAsyncScope (node:async_hooks:204:9)\n    at done (/home/kol/Projects/safe/packages/server/node_modules/fastify/lib/contentTypeParser.js:186:14)\n    at Parser.setMultipart [as fn] (/home/kol/Projects/safe/packages/server/node_modules/@fastify/multipart/index.js:35:3)\n    at ContentTypeParser.run (/home/kol/Projects/safe/packages/server/node_modules/fastify/lib/contentTypeParser.js:177:27)"},"msg":"Cannot read properties of undefined (reading 'Symbol(multipartHandler)')"}
[0] [1] [0] {"level":30,"time":1676620072964,"pid":85757,"hostname":"arch","reqId":"req-9","res":{"statusCode":500},"responseTime":8.288734000176191,"msg":"request completed"}
```

### Steps to Reproduce

on server
```typescript
(async () => {
  const fastify = Fastify({
    logger: FASTIFY_LOGGER,
  });

  await fastify.register(import('@fastify/middie'));
  await fastify.use(cors({ origin: [APP_URL] }));
  await fastify.register(import('@fastify/multipart'));

  fastify.use([Api.getUserFindFirst, Api.postFileUpload], checkTokenMiddleware);

  fastify.post(Api.postFileUpload, fileUpload);

  fastify.listen({ port: PORT, host: HOST }, (err, address) => {
    if (err) throw err;
    console.log('Server listenning on', address);
  });
})();

const fileUpload: RequestHandler<any, SendMessageArgs<MessageType.SET_FILE_UPLOAD>> = async (
  req,
  reply
) => {
  const { headers, file } = req;
  const { lang, id, timeout } = parseHeaders(headers);

  const f = await file();
  console.log(f);

  reply.type(APPLICATION_JSON).code(200);
  return {
    type: MessageType.SET_FILE_UPLOAD,
    id,
    lang,
    timeout: parseInt(timeout, 10),
    data: null,
  };
};

const checkTokenMiddleware: MiddleHandler = async (req, res, next) => {
  return next();
};
```

on client
```typescript
const saveLocalFiles = async (_files: FileList) => {
    const formData = new FormData();
    for (let i = 0; _files[i]; i++) {
      formData.append(`file-${i}`, _files[i]);
    }
    const res = await request.fileUpload(formData);
    console.log(res);
  };
  
class Request {
  public async fileUpload(files: FormData) {
    return this.send({
      url: Api.postFileUpload,
      method: 'POST',
      body: files,
      contentType: 'multipart/form-data',
    });
  }
private async send({
    body,
    url,
    id,
    locale,
    method,
    contentType = APPLICATION_JSON,
  }: {
    url: string;
    id?: string;
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    body?: any;
    locale?: string;
    contentType?: string;
    method: 'GET' | 'POST' | 'UPDATE' | 'DELETE';
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
  }): Promise<any> {
    return new Promise((resolve) => {
      log('info', 'Send request', { method, url });
      fetch(`${SERVER}${url}`, {
        body: body ? (contentType === APPLICATION_JSON ? JSON.stringify(body) : body) : undefined,
        method,
        headers: {
          [LANGUAGE_HEADER]: getCookie(CookieName.lang) || locale || LOCALE_DEFAULT,
          [USER_ID_HEADER]: id || getCookie(CookieName._uuid) || '',
          [AUTHORIZATION_HEADER]: getCookie(CookieName._utoken) || '',
          [TIMEOUT_HEADER]: new Date().getTime().toString(),
          'Content-Type': contentType,
        },
      })
        .then((d) => {
          resolve(d.json());
        })
        .catch((err) => {
          log('error', 'Request error', err);
          resolve({
            status: 'error',
            message: 'Internet error',
            code: 503,
            data: null,
            // eslint-disable-next-line @typescript-eslint/no-explicit-any
          } as Result<any>);
        });
    });
  }
}
```

### Expected Behavior

The request handler is expected to print the file data to the console and return a successful result to the client.

**Comment by climba03003** [comment]
Do not spread the `variables` out of `request` when the variable is `function`.
It will lost it's own context.
