### ISSUE TITLE
Only handle first file

### ISSUE THREAD

**Issue by ToonvanStrijp** [fastify/fastify-multipart#43]
How do I make it so that it only handles the first file and ignores the other once?
 I can't figure it out. My code now looks like this:

```
 await new Promise((resolve, reject) => {

      const body = {};

      const mp = req.multipart(handler, (err) => {
        console.log('finished');
        req.body = body;
        resolve();
      });


      function handler (field, file, filename, encoding, mimetype) {
        const saveTo = path.join(os.tmpdir(), path.basename(filename));
        file.pipe(fs.createWriteStream(saveTo));
      }

      mp.on('field', (key, value)  => {
        body[key] = value;
      });

    });
```

**Comment by ToonvanStrijp** [comment]
When I call `file.destory()` I get the following error:

```
Error: stream.push() after EOF
    at readableAddChunk (_stream_readable.js:240:30)
    at FileStream.Readable.push (_stream_readable.js:208:10)
    at PartStream.onData (/Users/toonvanstrijp/Projects/briter/briter-api-new/node_modules/busboy/lib/types/multipart.js:223:28)
    at emitOne (events.js:116:13)
    at PartStream.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at PartStream.Readable.push (_stream_readable.js:208:10)
    at Dicer._oninfo (/Users/toonvanstrijp/Projects/briter/briter-api-new/node_modules/dicer/lib/Dicer.js:191:36)
    at Dicer._oninfo (/Users/toonvanstrijp/Projects/briter/briter-api-new/node_modules/dicer/lib/Dicer.js:199:14)
    at SBMH.<anonymous> (/Users/toonvanstrijp/Projects/briter/briter-api-new/node_modules/dicer/lib/Dicer.js:127:10)
    at emitMany (events.js:147:13)
    at SBMH.emit (events.js:224:7)
    at SBMH._sbmh_feed (/Users/toonvanstrijp/Projects/briter/briter-api-new/node_modules/streamsearch/lib/sbmh.js:188:10)
    at SBMH.push (/Users/toonvanstrijp/Projects/briter/briter-api-new/node_modules/streamsearch/lib/sbmh.js:56:14)
    at Dicer._write (/Users/toonvanstrijp/Projects/briter/briter-api-new/node_modules/dicer/lib/Dicer.js:109:17)

```

**Comment by mcollina** [comment]
Some notes:

1. there is a security vulnerability in the code above, you need to escape the path because otherwise somebody can write a file everywhere in the filesystem.
2. you should use `pump` instead of  `pipe`, see https://www.npmjs.com/package/pump.

Can you provide a full example? You can also send a PR with a failing test.

**Comment by ToonvanStrijp** [comment]
@mcollina my finished is called before all the files are processed:

```
 await new Promise((resolve, reject) => {
      const body = {};
      const files = [];

      const mp = req.multipart(handler, (err) => {
        console.log('finished');
        req.body = body;
        console.log(files);
        resolve();
      });


      function handler (field, file, filename, encoding, mimetype) {
        const saveTo = path.join(os.tmpdir(), path.basename(filename));
        pump(file, fs.createWriteStream(saveTo), (err) => {
          console.log('processed file');
          files.push(saveTo);
        });
      }

      mp.on('field', (key, value)  => {
        body[key] = value;
      });

    });
```

**Comment by mcollina** [comment]
As I said, can you please upload a full example, including a way to to verify this behavior?

Adding a failing test in https://github.com/fastify/fastify-multipart/blob/master/test.js would be ok.

**Comment by ToonvanStrijp** [comment]
I've updated the index.js of the library:

change this
```
stream.on('finish', function () {
      log.debug('finished multipart parsing')
      done()
})
```
to:
```
stream.on('finish', function () {
      log.debug('finished multipart parsing')
      setTimeout(() => done())
})
```

Now it works fine! Sorry I don't know how to make a PR 😅

**Comment by mcollina** [comment]
maybe this can be of of help:
https://help.github.com/articles/creating-a-pull-request-from-a-fork/
Il giorno mar 3 lug 2018 alle 20:40 Toon van Strijp <
notifications@github.com> ha scritto:
