### ISSUE TITLE
promise error

### ISSUE THREAD

**Issue by johntom** [fastify/fastify-multipart#73]
1 .the following code always gives error even though it uploads
```
const multipart = require('fastify-multipart');
const fs = require('fs');
const concat = require('concat-stream')
const pump = require('pump')
module.exports = async function (fastify, opts) {
    fastify.register(require('fastify-multipart'))
    fastify.post('/upload', async (req, reply) => {
        const mp = req.multipart(handler, function (err) {
            console.log('upload completed')
            reply.code(200).send()
        })
        // mp is an instance of
        // https://www.npmjs.com/package/busboy
        mp.on('field', function (key, value) {
            console.log('form-data', key, value)
        })
        function handler(field, file, filename, encoding, mimetype) {
            pump(file, fs.createWriteStream(`./uploads/${filename}`))
      
        }
    })
}
```
error
```
form-data dir up1
{"level":50,"time":1559095846898,"pid":4316,"hostname":"John-lenovo","reqId":1,"err":{"type":"FastifyError","message":"FST_ERR_PROMISE_NOT_FULLFILLED: Promise may not be fulfilled with 'undefined' when statusCode is not 204","stack":"FastifyError [FST_ERR_PROMISE_NOT_FULLFILLED]: FST_ERR_PROMISE_NOT_FULLFILLED: Promise may not be fulfilled with 'undefined' when statusCode is not 204\n    at C:\\Frameworks\\Fastify\\gen\\demo1\\node_modules\\fastify\\lib\\wrapThenable.js:34:30\n    at process._tickCallback (internal/process/next_tick.js:68:7)","name":"FastifyError [FST_ERR_PROMISE_NOT_FULLFILLED]","code":"FST_ERR_PROMISE_NOT_FULLFILLED","statusCode":500},"msg":"Promise may not be fulfilled with 'undefined' when statusCode is not 204","v":1}
upload completed
{"level":30,"time":1559095846904,"pid":4316,"hostname":"John-lenovo","reqId":1,"res":{"statusCode":200},"responseTime":15.528599001467228,"msg":"request completed","v":1}

```
Before I do the upload I need to check the 'form-data; value and create a directory if it does not exist. I've not succeeded in any attempts as the handler is called before I get form data.

**Comment by Eomm** [comment]
I think your problem is related to [the promise resolution](https://github.com/fastify/fastify/blob/master/docs/Routes.md#promise-resolution)

If you write:
- `reply.code(200).send('uploaded')` 
- or `reply.code(204).send()`

should solve

**Comment by johntom** [comment]
I tried that and still get
```
{"level":30,"time":1559143173510,"pid":3704,"hostname":"JRT-PC","msg":"Server
listening at http://127.0.0.1:3000","v":1}
{"level":30,"time":1559143186558,"pid":3704,"hostname":"JRT-PC","reqId":1,"req":{"method":"POST","url":"/upload","hostname":"localhost:3000","remoteAddress":"127.0.0.1","remotePort":53226},"msg":"incoming
request","v":1}
{"level":50,"time":1559143186568,"pid":3704,"hostname":"JRT-PC","reqId":1,"err":{"type":"FastifyError","message":"FST_ERR_PROMISE_NOT_FULLFILLED:
Promise may not be fulfilled with 'undefined' when statusCode is not
204","stack":"FastifyError [FST_ERR_PROMISE_NOT_FULLFILLED]:
FST_ERR_PROMISE_NOT_FULLFILLED: Promise may not be fulfilled with
'undefined' when statusCode is not 204\n    at
C:\\Frameworks\\Fastify\\demo1\\node_modules\\fastify\\lib\\wrapThenable.js:34:30\n
   at process._tickCallback
(internal/process/next_tick.js:68:7)","name":"FastifyError
[FST_ERR_PROMISE_NOT_FULLFILLED]","code":"FST_ERR_PROMISE_NOT_FULLFILLED","statusCode":500},"msg":"Promise
may not be fulfilled with 'undefined' when statusCode is not 204","v":1}
upload completed
{"level":30,"time":1559143186578,"pid":3704,"hostname":"JRT-PC","reqId":1,"res":{"statusCode":200},"responseTime":20.077401000075042,"msg":"request
completed","v":1}
```

**Comment by johntom** [comment]
Hi,
I just wanted to share my solution for creating directories as passed in from form-data.
npm install fs-extra
```

//https://github.com/fastify/fastify-multipart
const multipart = require('fastify-multipart');
const concat = require('concat-stream')
const pump = require('pump')
const fs = require('fs-extra')
module.exports = async function (fastify, opts) {

    fastify.register(require('fastify-multipart'))
    fastify.post('/upload', async (req, reply) => {
        let uploaded = false
       let mp = req.multipart(handler, function (err) {
            console.log('upload completed')
            // reply.code(200).send()
            reply.code(200).send('uploaded')
        })

        // mp is an instance of https://www.npmjs.com/package/busboy
        let dirval = 0
        // check if directory exits passed as part of form
        mp.on('field', async function (key, value) {
            dirval = value;
            //console.log(' 2 mp.on', dirval)
            let pathcheck = `./uploads/${dirval}`
            fs.ensureDir(pathcheck)
                .then(() => {
                 //   console.log('success!')
                })
                .catch(err => {
                    console.error(err)
                })
        })
        async function handler(field, file, filename, encoding, mimetype) {
        
            await pump(file, fs.createWriteStream(`./uploads/${dirval}/${filename}`))
            uploaded = true
            // be careful of permission issues on disk and not overwrite ${dirval}
            // sensitive files that could cause security risks
        }
    })
}
```
While the code works as designed and tested uploading many files at once I still get error in console but does not seem to affect anything.
```
{"level":30,"time":1559338203772,"pid":8880,"hostname":"John-lenovo","reqId":1,"req":{"method":"POST","url":"/upload","hostname":"localhost:3000","remoteAddress":"127.0.0.1","remotePort":62750},"msg":"incoming request","v":1}
{"level":50,"time":1559338203791,"pid":8880,"hostname":"John-lenovo","reqId":1,"err":{"type":"FastifyError","message":"FST_ERR_PROMISE_NOT_FULLFILLED: Promise may not be fulfilled with 'undefined' when statusCode is not 204","stack":"FastifyError [FST_ERR_PROMISE_NOT_FULLFILLED]: FST_ERR_PROMISE_NOT_FULLFILLED: Promise may not be fulfilled with 'undefined' when statusCode is not 204\n    at C:\\Frameworks\\Fastify\\gen\\demo2\\node_modules\\fastify\\lib\\wrapThenable.js:34:30\n    at process._tickCallback (internal/process/next_tick.js:68:7)","name":"FastifyError [FST_ERR_PROMISE_NOT_FULLFILLED]","code":"FST_ERR_PROMISE_NOT_FULLFILLED","statusCode":500},"msg":"Promise may not be fulfilled with 'undefined' when statusCode is not 204","v":1}
upload completed
{"level":30,"time":1559338205941,"pid":8880,"hostname":"John-lenovo","reqId":1,"res":{"statusCode":200},"responseTime":2168.2824000120163,"msg":"request completed","v":1}
```

**Comment by Eomm** [comment]
Hi, it's good to solve. I would like to be sure that your log doesn't hide any problem since it is not good that line 👍🏼

**Comment by johntom** [comment]
How can I show you the log? Not sure what you mean.
Thks

**Comment by johntom** [comment]
I placed code in repo https://github.com/johntom/Fastify-Demo2

**Comment by Eomm** [comment]
The problem in the logs are due to the route handler:

https://github.com/johntom/Fastify-Demo2/blob/a8ef53de183896280f87a7cfa2c7ed2305d1e22e/app/services/uploadformdata/index.js#L12

if you use async, you should use await because this is an example of what it is happening:

```
const x = async () => {
  // callback registration for async code
}

const y = function () {
  return new Promise(() => {
    // never fulfilled promise
  })
}
x().then((res) => console.log(`x ${res}`))
y().then((res) => console.log(`y ${res}`))

setInterval(() => {
  // keep the promise wating
}, 3000)
```

The `x` fulfil immediately the promise created by the async and return `undefined` sooner than the handling of the file-upload.

So to fix you need to remove the `async` from the route handler or change the code to await the `req.multipart` final callback

**Comment by johntom** [comment]
Removing async worked, will test with async/await later. Funny how I
usually get this right but I guess not all the time:)

**Comment by Eomm** [comment]
We solved ✌
